version: '3.8'

services:
  backend:
    build: ./backend
    container_name: helper-app-backend
    restart: unless-stopped
    ports:
      - "3001:3001"
    volumes:
      - ./backend/data.db:/app/data.db
      - ./backend/uploads:/app/uploads
    environment:
      - PORT=3001
      - NODE_ENV=production
    networks:
      - helper-network

  frontend:
    build: .
    container_name: helper-app-frontend
    restart: unless-stopped
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - helper-network

networks:
  helper-network:
    driver: bridge
